baseurl = "/"
title = "Terrassa"
author = "Daniel Zaragoza (Danielkvist)"
googleAnalytics = ""
defaultContentLanguage = "en"
paginate = 3
theme = "terrassa"
themesDir = "themes"
baseURL = ""
publishDir = "public"

[params]
description = "Terrassa is a simple, fast and responsive theme for Hugo with a strong focus on accessibility made from scratch."
favicon = "favicon.ico"
logo = ""

  [params.hero]
  textColor = ""

  [params.cta]
  show = true
  cta = "Contact"
  link = "contact"

  [params.separator]
  show = false

  [params.fa]
  version = "5.7.2"
  integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

  [params.form]
  netlify = true
  action = "https://formspree.io/your@email.com"
  method = "POST"
  inputNameName = "name"
  inputNameLabel = "Name"
  inputNamePlaceholder = "Your name"
  inputEmailName = "email"
  inputEmailLabel = "Email"
  inputEmailPlaceholder = "Your email"
  inputMsgName = "message"
  inputMsgLabel = "Write something"
  inputMsgLength = 750
  inputSubmitValue = "Send"

  [params.posts]
  showAuthor = true
  showDate = true
  showTags = true
  dateFormat = "Monday, Jan, 2006"

  [params.contact]
  email = "example@gmail.com"
  phone = "xxx xxx xxx"
  skype = ""
  address = "419 Creek St. Revere, MA 02151"

  [params.social]
  twitter = "https://twitter.com/john"
  facebook = "https://facebook.com/john"
  github = "https://github.com/john"
  gitlab = ""
  codepen = "https://codepen.io/john"
  instagram = "https://instagram.com/john"
  pinterest = ""
  youtube = ""
  linkedin = ""
  weibo = ""
  mastodon = ""
  tumblr = ""
  flickr = ""
  500px = ""

  [params.copy]
  copy = ""

  [params.languageSwitcher]
  show = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = false
simple = false

[privacy.twitter]
disable = false
enableDNT = true
simple = false

[privacy.vimeo]
disable = false
simple = false

[privacy.youtube]
disable = false
privacyEnhanced = true

[languages.en]
languageName = "en"
weight = 1
contentDir = "content/en"

[languages.de]
languageName = "de"
weight = 2
contentDir = "content/de"
title = "Das ist der deutsche Titel"
description = "Das ist die deutsche Beschreibung"

[languages.de.params.form]
inputNameLabel = "Name"
inputNamePlaceholder = "Dein Name"
inputEmailLabel = "E-mail"
inputEmailPlaceholder = "Deine E-Mail-Adresse"
inputMsgLabel = "Schreib etwas"
inputSubmitValue = "Abschicken"

[languages.de.params.cta]
show = true
cta = "Kontakt"
link = "de/kontakt/"
